# Generated by Django 6.1.1 on 2026-09-30 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_index=True, max_length=1000)),
                ('language', models.CharField(default='python', max_length=50)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('is_test_file', models.BooleanField(db_index=True, default=False)),
                ('total_lines', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'code_files',
                'ordering': ['file_path'],
            },
        ),
        migrations.CreateModel(
            name='CodeComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('qualified_name', models.CharField(db_index=True, max_length=500)),
                ('component_type', models.CharField(choices=[('MODULE', 'Module'), ('CLASS', 'Class'), ('FUNCTION', 'Function'), ('METHOD', 'Method'), ('VARIABLE', 'Variable')], default='FUNCTION', max_length=20)),
                ('start_line', models.PositiveIntegerField()),
                ('end_line', models.PositiveIntegerField()),
                ('docstring', models.TextField(blank=True, default='')),
                ('parameters', models.JSONField(blank=True, default=list)),
                ('is_test', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_components', to='projects.codecomponent')),
                ('code_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='projects.codefile')),
            ],
            options={
                'db_table': 'code_components',
                'ordering': ['code_file', 'start_line'],
            },
        ),
        migrations.CreateModel(
            name='ComponentDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('CALLS', 'Calls'), ('INHERITS', 'Inherits'), ('IMPORTS', 'Imports'), ('REFERENCES', 'References')], default='CALLS', max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='projects.codecomponent')),
                ('target_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='projects.codecomponent')),
            ],
            options={
                'db_table': 'component_dependencies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='python', max_length=50)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='codefile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project'),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_cloned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('CLONING', 'Cloning'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='IDLE', max_length=20)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='projects.project')),
            ],
            options={
                'db_table': 'repositories',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(db_index=True, max_length=64)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('author_email', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_hashes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='projects.repository')),
            ],
            options={
                'db_table': 'commits',
                'ordering': ['-committed_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='codecomponent',
            index=models.Index(fields=['qualified_name'], name='code_compon_qualifi_f8b6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='codecomponent',
            index=models.Index(fields=['component_type'], name='code_compon_compone_7c9c33_idx'),
        ),
        migrations.AddConstraint(
            model_name='componentdependency',
            constraint=models.UniqueConstraint(fields=('source_component', 'target_component', 'dependency_type'), name='unique_dependency_edge'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_user_project_name'),
        ),
        migrations.AddConstraint(
            model_name='codefile',
            constraint=models.UniqueConstraint(fields=('project', 'file_path'), name='unique_project_file'),
        ),
        migrations.AddConstraint(
            model_name='commit',
            constraint=models.UniqueConstraint(fields=('repository', 'commit_hash'), name='unique_repo_commit'),
        ),
    ]
