# Generated by Django 6.1.1 on 2026-09-30 10:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('analysis_type', models.CharField(choices=[('COMMIT', 'Commit'), ('BRANCH_DIFF', 'Branch Diff'), ('CUSTOM_DIFF', 'Custom Diff')], default='COMMIT', max_length=20)),
                ('target_commit_hash', models.CharField(blank=True, default='', max_length=64)),
                ('base_commit_hash', models.CharField(blank=True, default='', max_length=64)),
                ('diff_content', models.TextField(blank=True, default='')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('stage_message', models.CharField(blank=True, default='Initialized', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('traceback_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_risk_score', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=20)),
                ('risk_score_numeric', models.FloatField(default=0.0)),
                ('total_changed_files', models.PositiveIntegerField(default=0)),
                ('total_changed_components', models.PositiveIntegerField(default=0)),
                ('total_impacted_components', models.PositiveIntegerField(default=0)),
                ('total_affected_tests', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('risk_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangedComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=255)),
                ('qualified_name', models.CharField(max_length=500)),
                ('change_type', models.CharField(choices=[('ADDED', 'Added'), ('MODIFIED', 'Modified'), ('DELETED', 'Deleted')], default='MODIFIED', max_length=20)),
                ('lines_added', models.PositiveIntegerField(default=0)),
                ('lines_deleted', models.PositiveIntegerField(default=0)),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('diff_snippet', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'changed_components',
                'ordering': ['file_path', 'start_line'],
            },
        ),
        migrations.CreateModel(
            name='ImpactedComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=255)),
                ('qualified_name', models.CharField(max_length=500)),
                ('impact_type', models.CharField(choices=[('DIRECT', 'Direct Impact'), ('TRANSITIVE', 'Transitive Impact')], default='TRANSITIVE', max_length=20)),
                ('depth', models.PositiveSmallIntegerField(default=1)),
                ('dependency_path', models.JSONField(blank=True, default=list)),
                ('is_test', models.BooleanField(db_index=True, default=False)),
                ('reason', models.TextField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
            ],
            options={
                'db_table': 'impacted_components',
                'ordering': ['-is_test', 'depth', 'qualified_name'],
            },
        ),
    ]
