# Generated by Django 6.1.1 on 2026-09-30 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysisjob'),
        ),
        migrations.AddField(
            model_name='changedcomponent',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='projects.codecomponent'),
        ),
        migrations.AddField(
            model_name='changedcomponent',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_components', to='analysis.analysisresult'),
        ),
        migrations.AddField(
            model_name='impactedcomponent',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impacts', to='projects.codecomponent'),
        ),
        migrations.AddField(
            model_name='impactedcomponent',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacted_components', to='analysis.analysisresult'),
        ),
    ]
